(function(){
const start=new Date('2026-08-08T00:00:00+01:00'),end=new Date('2026-08-24T23:59:59+01:00');
const D=['Funchal','Monte','Jardin botanique','Câmara de Lobos','Cabo Girão','Prainha','Pico do Arieiro','Santana','Machico','Ponta de São Lourenço','Caniçal','Fanal','Porto Moniz','Ribeira Brava','Caniçal','Journée flexible','Aéroport'];
const css=document.createElement('style');css.textContent='.hero:after{content:"V1.7"!important}.v17today{max-width:920px;margin:14px auto;padding:0 12px}.v17card{background:linear-gradient(145deg,#102d25,#1f6251);color:#fff;border-radius:22px;padding:18px;box-shadow:0 14px 35px rgba(10,40,31,.16)}.v17eyebrow{font-size:.72rem;font-weight:900;letter-spacing:.1em;text-transform:uppercase;opacity:.72}.v17title{font-size:1.35rem;font-weight:900;margin:5px 0}.v17meta{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.v17meta span{background:rgba(255,255,255,.12);padding:7px 9px;border-radius:10px;font-size:.78rem;font-weight:800}.v17actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.v17actions a{background:#fff;color:#0f6f5f;text-decoration:none;padding:10px 12px;border-radius:11px;font-weight:900;font-size:.8rem}.v17decision{margin:10px 0;padding:11px 13px;border-radius:13px;font-size:.8rem;font-weight:800;background:#eef7f4;color:#245b4c}.v17decision.warn{background:#fff1df;color:#79511a}.v17decision.bad{background:#ffe7e3;color:#8a3028}.v17filterinfo{max-width:920px;margin:10px auto 18px;padding:0 12px}.v17filterbox{background:#fff;border:1px solid #dce6e1;border-radius:20px;padding:17px;box-shadow:0 8px 25px rgba(20,55,45,.07)}.v17filterbox h3{margin:0 0 5px;color:#173b31}.v17filterbox p{margin:0 0 12px;color:#61736c}.v17filterdays{display:grid;gap:8px}.v17filterdays a{display:block;background:#f3f8f6;border-radius:13px;padding:11px 12px;color:#173b31;text-decoration:none;font-weight:800}.v17filterdays small{display:block;color:#718078;font-weight:600;margin-top:2px}@media(max-width:560px){.v17title{font-size:1.18rem}}';document.head.appendChild(css);
function dayNo(x){if(x<start)return 0;if(x>end)return 18;return Math.floor((x-start)/86400000)+1}
const now=new Date(),n=dayNo(now),dash=document.querySelector('.v12dash')||document.querySelector('.summary');
if(dash){const s=document.createElement('section');s.className='v17today';let html='';if(n===0){const days=Math.ceil((start-now)/86400000);html='<div class="v17card"><div class="v17eyebrow">Votre prochain voyage</div><div class="v17title">Madère commence dans '+days+' jour'+(days>1?'s':'')+'</div><div class="v17meta"><span>✈️ 8 août 2026</span><span>🌿 17 journées</span><span>📍 Madère</span></div><div class="v17actions"><a href="#day-1">Voir J1</a></div></div>';}else if(n<=17){html='<div class="v17card"><div class="v17eyebrow">Aujourd’hui · J'+n+'</div><div class="v17title">'+D[n-1]+'</div><div class="v17meta"><span>📍 '+D[n-1]+'</span><span id="v17todaywx">🌦️ météo en cours…</span><span id="v17todaygo">⏳ analyse</span></div><div class="v17actions"><a href="#day-'+n+'">Ouvrir ma journée</a><a target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(D[n-1]+' Madeira')+'">Itinéraire</a></div></div>';}else html='<div class="v17card"><div class="v17eyebrow">Madère 2026</div><div class="v17title">Votre voyage est terminé ❤️</div><div class="v17actions"><a href="#day-1">Revoir le programme</a></div></div>';s.innerHTML=html;dash.insertAdjacentElement('afterend',s);}
function getTitle(day,i){return day?.querySelector('.day-head h2,.day-head h3,h2,h3')?.textContent?.trim()||D[i-1]}
function filterInfo(kind){document.querySelector('.v17filterinfo')?.remove();if(kind==='Tout')return;const words={Famille:/famille|Sofia|enfant/i,'À deux':/à deux|couple/i,Sport:/sport|crossfit|run|trail|course|randonnée/i};const rx=words[kind];let rows=[];for(let i=1;i<=17;i++){const day=document.getElementById('day-'+i);if(!day)continue;const text=day.innerText||'';if(rx.test(text)){let detail='';const body=day.querySelector('.day-body');if(body){const lines=(body.innerText||'').split('\n').map(x=>x.trim()).filter(Boolean);detail=lines.find(x=>rx.test(x)&&x.length>12)||lines.find(x=>x.length>25)||'';}rows.push('<a href="#day-'+i+'">J'+i+' · '+getTitle(day,i)+'<small>'+detail.slice(0,120)+'</small></a>');}}
const box=document.createElement('section');box.className='v17filterinfo';box.innerHTML='<div class="v17filterbox"><h3>'+(kind==='Sport'?'🏃 Tout le sport prévu':kind==='Famille'?'👨‍👩‍👧 Programme famille':'❤️ Programme à deux')+'</h3><p>'+rows.length+' journée'+(rows.length>1?'s':'')+' concernée'+(rows.length>1?'s':'')+'. Touchez une journée pour aller directement au détail.</p><div class="v17filterdays">'+rows.join('')+'</div></div>';const target=document.querySelector('.v17today')||dash;target.insertAdjacentElement('afterend',box);box.scrollIntoView({behavior:'smooth',block:'start'});}
function wire(){const labels=['Tout','Famille','À deux','Sport'];document.querySelectorAll('button,a').forEach(el=>{const t=(el.textContent||'').trim();if(labels.includes(t)&&!el.dataset.v17wired){el.dataset.v17wired='1';el.addEventListener('click',()=>setTimeout(()=>filterInfo(t),50));}})}wire();setTimeout(wire,1200);
function decisions(){for(let i=1;i<=17;i++){const day=document.getElementById('day-'+i),wx=day?.querySelector('.v14swap');if(!day||!wx||day.querySelector('.v17decision'))continue;const t=wx.textContent||'';let c='v17decision',msg='🟢 Programme conseillé tel quel.';if(/échange|Mieux vaut/i.test(t)){c+=' bad';msg='🔴 Conseil : permuter cette journée. Consulte les alternatives météo.'}else if(/moyennes|surveiller/i.test(t)){c+=' warn';msg='🟠 À surveiller : vérifie la météo le matin avant de partir.'}const e=document.createElement('div');e.className=c;e.textContent=msg;wx.insertAdjacentElement('afterend',e);}if(n>=1&&n<=17){const w=document.querySelector('#day-'+n+' .v14wx'),go=document.getElementById('v17todaygo'),tw=document.getElementById('v17todaywx');if(w&&go){const tx=w.textContent||'';go.textContent=/Mieux vaut|échange/i.test(tx)?'🔴 PERMUTER':/moyennes/i.test(tx)?'🟠 À surveiller':/favorables/i.test(tx)?'🟢 GO':'⏳ analyse';if(tw){const temp=w.querySelector('.v14wxgrid span');tw.textContent=temp?'🌦️ '+temp.textContent.trim():'🌦️ météo locale';}}}}
setTimeout(decisions,1800);setInterval(decisions,10000);const f=document.querySelector('footer');if(f)f.textContent=f.textContent.replace(/V1\.[0-9]+/,'V1.7');
})();